import * as PRaw from './permissions';
const P: any = PRaw;

export const STUDENT_PERMS =
  P.RES_CREATE |
  P.RES_READ |
  P.ROOM_READ |
  P.CLASS_READ;

export const TEACHER_PERMS =
  STUDENT_PERMS |
  P.RES_UPDATE |
  P.RES_CANCEL |
  P.ROOM_UPDATE;

export const ADMIN_PERMS =
  P.USER_CREATE | P.USER_READ | P.USER_UPDATE | P.USER_DELETE |
  P.ROOM_CREATE | P.ROOM_READ | P.ROOM_UPDATE | P.ROOM_DELETE |
  P.CLASS_CREATE | P.CLASS_READ | P.CLASS_UPDATE | P.CLASS_DELETE |
  P.RES_CREATE | P.RES_READ | P.RES_UPDATE | P.RES_CANCEL |
  P.ADMIN_ALL;
